CREATE EVENT clearExpiredAds
ON SCHEDULE EVERY 1 DAY
STARTS CURRENT_DATE + INTERVAL 23 HOUR + INTERVAL 59 MINUTE ON COMPLETION PRESERVE ENABLE
DO DELETE FROM `adsky_ads` WHERE `until` <= UNIX_TIMESTAMP(CONVERT_TZ(DATE(NOW()), '+00:00', 'SYSTEM'));