<?php

$settings['AD_PER_DAY_LIMIT'] = 15;

$settings['AD_TITLE_COST'] = 1.0;
$settings['AD_TITLE_LIMIT_TITLE_CHARS_MIN'] = 2;
$settings['AD_TITLE_LIMIT_TITLE_CHARS_MAX'] = 20;
$settings['AD_TITLE_LIMIT_MESSAGE_CHARS_MIN'] = 0;
$settings['AD_TITLE_LIMIT_MESSAGE_CHARS_MAX'] = 30;
$settings['AD_TITLE_LIMIT_DAY_MIN'] = 1;
$settings['AD_TITLE_LIMIT_DAY_MAX'] = 4;
$settings['AD_TITLE_LIMIT_SECONDS_MIN'] = 4;
$settings['AD_TITLE_LIMIT_SECONDS_MAX'] = 6;
$settings['AD_TITLE_LIMIT_EXPIRATION_MIN'] = 1;
$settings['AD_TITLE_LIMIT_EXPIRATION_MAX'] = 31;

$settings['AD_CHAT_COST'] = 0.2;
$settings['AD_CHAT_LIMIT_TITLE_CHARS_MIN'] = 2;
$settings['AD_CHAT_LIMIT_TITLE_CHARS_MAX'] = 20;
$settings['AD_CHAT_LIMIT_MESSAGE_CHARS_MIN'] = 0;
$settings['AD_CHAT_LIMIT_MESSAGE_CHARS_MAX'] = 140;
$settings['AD_CHAT_LIMIT_DAY_MIN'] = 1;
$settings['AD_CHAT_LIMIT_DAY_MAX'] = 12;
$settings['AD_CHAT_LIMIT_EXPIRATION_MIN'] = 1;
$settings['AD_CHAT_LIMIT_EXPIRATION_MAX'] = 31;